name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ---- FASTAPI (Python) ----
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install FastAPI dependencies
      working-directory: ./WasteWatchAIFastApi
      run: pip install -r requirements.txt

    - name: Run FastAPI tests
      working-directory: ./WasteWatchAIFastApi
      run: pytest tests/

    # ---- .NET Core API ----
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore .NET dependencies
      working-directory: ./WasteWatchAIBackend
      run: dotnet restore

    - name: Build .NET API
      working-directory: ./WasteWatchAIBackend
      run: dotnet build --configuration Release

    - name: Test .NET API
      working-directory: ./WasteWatchAIBackend
      run: dotnet test --configuration Release

    # ---- BLAZOR Frontend ----
    - name: Restore Blazor dependencies
      working-directory: ./WasteWatchAIFrontend
      run: dotnet restore

    - name: Build Blazor
      working-directory: ./WasteWatchAIFrontend
      run: dotnet build --configuration Release
